[build]
target = ["aarch64-unknown-uefi", "x86_64-unknown-uefi"]

[target.aarch64-unknown-uefi]
runner = "cargo +nightly -Zscript ./scripts/qemu.rs aarch64-unknown-uefi"

[target.x86_64-unknown-uefi]
runner = "cargo +nightly -Zscript ./scripts/qemu.rs x86_64-unknown-uefi"

[unstable]
build-std = ["alloc", "core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
